scriptTime: 100
programTime: 3000
SyscallsFileName: "/etc/lmu/lmuSyscalls.yaml"
outputPath: "."
lsofBinPath: "/usr/bin/lsof"
rpmBinPath: "/usr/bin/rpm"
bpftraceBinPath: "/usr/bin/bpftrace"
tmpPath: "."
tmpDelete: true
BPFTRACE_STRLEN : "128"
BPFTRACE_MAP_KEYS_MAX : "100000"
DirToIgnore:
  - /proc/
  - /dev/
  - /sys/